name: pill_reminder
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  
  #State Management
  provider: ^6.0.5

  #Database
  hive_flutter: ^1.1.0

  #Utility
  awesome_notifications: ^0.7.4
  path_provider: ^2.1.0
  google_fonts: ^5.1.0
  intl_utils: ^2.8.3
  auto_route: ^7.7.1
  equatable: ^2.0.5
  uuid: ^3.0.7

  #Widget
  day_night_time_picker: ^1.3.0
  font_awesome_flutter: ^10.5.0
  day_picker: ^2.2.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 
  hive_generator: ^2.0.0
  auto_route_generator: ^7.2.0

  flutter_lints: ^2.0.0
dependency_overrides:
  intl: ^0.18.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/


  

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

